[package]
name = "aoc18"
version = "0.1.0"
authors = ["Olivier Pinon <oliv.pinon@gmail.com>"]
edition = "2018"

[dependencies]
fnv = "1.0.6"
aoc-runner = "*"
aoc-runner-derive = "*"
edit-distance = "2.0.1"
rayon = "1.0.3"
chrono = "0.4.6"
